ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
#FROM repo.asax.ir/elasticsearch/elasticsearch:${ELASTIC_VERSION}
FROM repo.asax.ir/asa/bi/tools/elasticsearch:${ELASTIC_VERSION}
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
